"""Persist a synthetic recorder example outside the official business result tree.

Usage: python docs/atdd/web/generate_tool_sample.py
The sample is deliberately FAIL and cannot count as product acceptance.
"""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import patch

import record_result as recorder
from validate_result import ROOT, read_json, sha256, validate_result


SAMPLE = ROOT / "docs" / "atdd" / "web" / "evidence" / "WEB-02" / "tool-sample"
CASE_ID = "WEB-DATA-09"


def main() -> None:
    ledger = SAMPLE / "execution-progress.sample.json"
    plan = SAMPLE / "execution-plan.sample.md"
    observation_path = SAMPLE / "observation.sample.json"
    result_dir = SAMPLE / "evidence" / "synthetic-tool" / CASE_ID / "api-fixture"
    result_dir.mkdir(parents=True, exist_ok=True)
    ledger.write_bytes((ROOT / "docs/atdd/web/execution-progress.json").read_bytes())
    plan.write_text(
        "# Synthetic recorder fixture; no business acceptance\n\n"
        "## 7. 决策与偏差记录\n",
        encoding="utf-8",
    )
    (result_dir / "a.txt").write_text(
        "Synthetic negative result generated by WEB-02 tooling.\n",
        encoding="utf-8",
    )
    observation = {
        "caseId": CASE_ID,
        "runId": "synthetic-tool",
        "variant": "api-fixture",
        "status": "FAIL",
        "build": {
            "appVersion": "tool-fixture",
            "gitCommit": "abcdef0",
            "apiVersion": "tool-fixture",
        },
        "environment": {
            "kind": "api",
            "osName": "synthetic",
            "osVersion": "synthetic",
            "planTimezone": "Asia/Shanghai",
            "businessDate": "2026-09-28",
            "serverNowUtc": "2026-09-28T00:00:00Z",
            "network": "online",
        },
        "fixtureId": "synthetic-tool-fixture",
        "startedAt": "2026-09-28T00:00:00Z",
        "endedAt": "2026-09-28T00:01:00Z",
        "assertions": {
            "functional": {
                "actual": "Synthetic failure to test recorder propagation",
                "status": "FAIL",
                "evidencePaths": ["a.txt"],
            },
            "visual": {
                "actual": "API-only synthetic fixture",
                "status": "N_A",
                "evidencePaths": [],
            },
            "negative": {
                "actual": "Synthetic rejection observed",
                "status": "PASS",
                "evidencePaths": ["a.txt"],
            },
        },
        "evidence": [{"code": "A", "path": "a.txt", "mimeType": "text/plain"}],
        "reviewer": {
            "kind": "human",
            "name": "WEB-02-tool-fixture",
            "reviewedAt": "2026-09-28T00:02:00Z",
            "reason": "Synthetic recorder sample; not a product acceptance run",
        },
    }
    observation_path.write_text(
        json.dumps(observation, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    if (result_dir / "result.json").exists():
        (result_dir / "result.json").unlink()
    with (
        patch.object(recorder, "ROOT", SAMPLE),
        patch.object(recorder, "LEDGER", ledger),
        patch.object(recorder, "PLAN", plan),
        patch.object(
            recorder,
            "validate_result",
            lambda path: validate_result(path, enforce_path=False),
        ),
    ):
        result_path = recorder.record(observation_path)
    result = validate_result(result_path, enforce_path=False)
    snapshot = read_json(ledger)
    case = next(item for item in snapshot["caseLedger"] if item["caseId"] == CASE_ID)
    official = read_json(ROOT / "docs/atdd/web/execution-progress.json")
    official_case = next(item for item in official["caseLedger"] if item["caseId"] == CASE_ID)
    if result["status"] != "FAIL" or case["verificationStatus"] != "FAIL":
        raise RuntimeError("synthetic sample result was not propagated")
    if official_case["verificationStatus"] != "NOT_RUN":
        raise RuntimeError("official business case status unexpectedly changed")
    if "Synthetic failure to test recorder propagation" not in plan.read_text(encoding="utf-8"):
        raise RuntimeError("sample Markdown log was not updated")
    report = {
        "scope": "WEB-02 synthetic tool self-test; excludes product acceptance",
        "sampleResult": result_path.relative_to(SAMPLE).as_posix(),
        "sampleStatus": case["verificationStatus"],
        "officialCaseStatus": official_case["verificationStatus"],
        "files": {
            path.relative_to(SAMPLE).as_posix(): sha256(path)
            for path in sorted(SAMPLE.rglob("*"))
            if path.is_file() and path.name != "sample-check.json"
        },
    }
    (SAMPLE / "sample-check.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"validated synthetic result: {result_path}")
    print(f"sample ledger={case['verificationStatus']}; official ledger={official_case['verificationStatus']}")


if __name__ == "__main__":
    main()
