export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
export const errorCodes = [
  "VALIDATION_ERROR",
  "UNAUTHENTICATED",
  "FORBIDDEN",
  "NOT_FOUND",
  "RATE_LIMITED",
  "OTP_EXPIRED",
  "OTP_INVALID",
  "OTP_RATE_LIMITED",
  "SMS_UNAVAILABLE",
  "USERNAME_TAKEN",
  "PHONE_TAKEN",
  "PLAN_DATE_INVALID",
  "RULE_CHANGED",
  "CHECKIN_CONFLICT",
  "PLAN_NOT_ACTIVE",
  "IDEMPOTENCY_KEY_REUSED",
  "SHARE_REVOKED",
  "FRIEND_BLOCKED",
  "MEDIA_NOT_READY",
  "CURSOR_EXPIRED",
  "ACCOUNT_DELETION_PENDING",
] as const;
export type ApiErrorCode = (typeof errorCodes)[number];
/** A route tuple is method, path suffix, stable operation ID, and auth requirement. */
export const apiRoutes = [
  ["POST", "auth/sms/challenges", "createSmsChallenge", false],
  ["POST", "auth/sms/verify", "verifySmsChallenge", false],
  ["POST", "auth/refresh", "refreshSession", false],
  ["POST", "auth/logout", "logout", true],
  ["GET", "me", "getMe", true],
  ["PATCH", "me", "updateMe", true],
  ["GET", "usernames/availability", "checkUsername", true],
  ["POST", "me/change-phone/challenge", "createChangePhoneChallenge", true],
  ["POST", "me/change-phone/confirm", "confirmChangePhone", true],
  ["GET", "groups", "listGroups", true],
  ["POST", "groups", "createGroup", true],
  ["PATCH", "groups/{id}", "updateGroup", true],
  ["DELETE", "groups/{id}", "deleteGroup", true],
  ["GET", "plans", "listPlans", true],
  ["GET", "today", "getToday", true],
  ["GET", "calendar", "getGlobalCalendar", true],
  ["GET", "calendar/{businessDate}", "getCalendarDay", true],
  ["POST", "plans", "createPlan", true],
  ["GET", "plans/{id}", "getPlan", true],
  ["GET", "plans/{id}/detail", "getPlanDetail", true],
  ["PATCH", "plans/{id}", "updatePlan", true],
  ["POST", "plans/{id}/pause", "pausePlan", true],
  ["POST", "plans/{id}/resume", "resumePlan", true],
  ["POST", "plans/{id}/archive", "archivePlan", true],
  ["DELETE", "plans/{id}", "deletePlan", true],
  ["GET", "plans/{id}/calendar", "getPlanCalendar", true],
  ["PUT", "plans/{id}/checkins/{businessDate}", "putCheckin", true],
  ["GET", "plans/{id}/checkins/{businessDate}", "getCheckin", true],
  ["GET", "plans/{id}/statistics", "getPlanStatistics", true],
  ["POST", "plans/{id}/one-time-resolution", "createOneTimeResolution", true],
  ["PATCH", "plans/{id}/one-time-resolution", "reviseOneTimeResolution", true],
  ["POST", "media/upload-intents", "createUploadIntent", true],
  ["POST", "media/{id}/complete", "completeMedia", true],
  ["DELETE", "media/{id}", "deleteMedia", true],
  ["GET", "media/{id}/download-url", "getMediaDownloadUrl", true],
  ["GET", "users/search", "searchUsers", true],
  ["POST", "friend-requests", "createFriendRequest", true],
  ["GET", "friend-requests", "listFriendRequests", true],
  ["POST", "friend-requests/{id}/accept", "acceptFriendRequest", true],
  ["POST", "friend-requests/{id}/reject", "rejectFriendRequest", true],
  ["GET", "friends", "listFriends", true],
  ["DELETE", "friends/{id}", "deleteFriend", true],
  ["POST", "blocks", "createBlock", true],
  ["DELETE", "blocks/{id}", "deleteBlock", true],
  ["GET", "plans/{id}/share-preview", "getSharePreview", true],
  ["GET", "plans/{id}/shares", "listPlanShares", true],
  ["PUT", "plans/{id}/shares/{friendId}", "sharePlan", true],
  ["DELETE", "plans/{id}/shares/{friendId}", "revokePlanShare", true],
  ["GET", "friends/{id}/shared-plans", "listSharedPlans", true],
  ["GET", "shared-plans/{id}", "getSharedPlan", true],
  ["GET", "shared-plans/{id}/checkins", "listSharedCheckins", true],
  ["POST", "checkins/{id}/encouragements", "createEncouragement", true],
  ["GET", "checkins/{id}/encouragements", "listEncouragements", true],
  ["GET", "plans/{id}/reminder", "getReminder", true],
  ["PUT", "plans/{id}/reminder", "putReminder", true],
  ["POST", "devices/push-token", "registerPushToken", true],
  ["GET", "me/notification-preferences", "getNotificationPreferences", true],
  [
    "PATCH",
    "me/notification-preferences",
    "updateNotificationPreferences",
    true,
  ],
  ["GET", "sync/changes", "getSyncChanges", true],
  ["POST", "sync/ack", "ackSync", true],
  ["POST", "me/exports", "createExport", true],
  ["GET", "me/exports/{id}", "getExport", true],
  ["POST", "me/deletion-request", "requestDeletion", true],
  ["POST", "me/deletion-cancel", "cancelDeletion", true],
  ["GET", "me/deletion-status", "getDeletionStatus", true],
] as const satisfies ReadonlyArray<
  readonly [HttpMethod, string, string, boolean]
>;
