// Generated from docs/ui/plan-checkin-visual-tree.json and page map. Do not edit by hand.
export const penColors = {
  background: "#F8F9F6",
  surface: "#FFFFFF",
  primary: "#236B4A",
  text: "#17231C",
  secondary: "#7E8880",
} as const;

export const penScreens = [
  {
    key: "phone-login",
    groupId: "onboarding",
    order: 1,
    title: "手机号登录",
    frameId: "W4Wk7k",
    referenceImage: "uxpilot-export-09-27-26_13.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "O0D9o",
      "p7DfG4",
      "Wy2Ec",
      "fKNiv",
      "R1f73",
      "bfIsK",
      "H7WCT",
      "Qh2xX",
      "BUguK",
      "S1WME",
      "N9FLj8",
    ],
  },
  {
    key: "sms-code",
    groupId: "onboarding",
    order: 2,
    title: "验证码输入",
    frameId: "m10O6",
    referenceImage: "uxpilot-export-09-27-26_03.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "X7erC",
      "ZNlO4",
      "ALqnz",
      "hweRF",
      "u5WlQN",
      "Jg6kt",
      "w10R6a",
      "f4QKy",
      "oWEHo",
      "FNTVz",
      "uUV9z",
      "H9BqwG",
      "wnxwg",
      "PlRUq",
      "HTCIY",
      "k3SJqr",
      "xT18U",
      "nnNWJ",
      "qjsks",
      "IePHq",
      "l9HaM",
      "jXDez",
      "VU15y",
      "ucdVG",
      "c6LKA9",
      "vwg8G",
      "ngf6J",
    ],
  },
  {
    key: "profile-setup",
    groupId: "onboarding",
    order: 3,
    title: "设置昵称与头像",
    frameId: "y1XyY",
    referenceImage: "uxpilot-export-09-27-26_29.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "OHQgc",
      "t96jr",
      "V2KZtr",
      "HWtLH",
      "V8x752",
      "vNB0w",
      "RYnyw",
      "L949G8",
      "i25KO",
      "dDq3v",
      "OQ5la",
      "m8O1D",
      "Hx0sC",
    ],
  },
  {
    key: "today-empty",
    groupId: "today-records",
    order: 4,
    title: "今日空状态",
    frameId: "q68dDE",
    referenceImage: "uxpilot-export-09-27-26_08.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "uJlVq",
      "xJUuy",
      "vCI2m",
      "dlifv",
      "HH4O9",
      "ieD4b",
      "a7zAf",
      "aRznD",
      "fnEI4",
      "upc9D",
      "CjPGH",
      "w6jiJ",
      "SY5j6",
      "huhcv",
      "ACHek",
      "maQfG",
      "o9x3TG",
      "nLgqB",
      "dd5Dm",
      "O2f9Ef",
      "HaGiY",
    ],
  },
  {
    key: "today-active",
    groupId: "today-records",
    order: 5,
    title: "今日待处理",
    frameId: "C96GrU",
    referenceImage: "uxpilot-export-09-27-26_27.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "fjWj1",
      "ZF0zw",
      "zqFBz",
      "D402i5",
      "okAVn",
      "vT0tC",
      "f5pnWW",
      "T7lH5s",
      "AqXvH",
      "OuhiW",
      "K1bACK",
      "N570Y",
      "r5raY",
      "IaGQk",
      "Ykgj8",
      "eCSPi",
      "eHZH5",
      "BugGw",
      "uGh6w",
      "r2oHMz",
      "oHnzl",
      "fQw2j",
      "fD6B1",
      "h0gYm",
      "aOO3c",
      "beA6A",
    ],
  },
  {
    key: "checkin-do",
    groupId: "today-records",
    order: 6,
    title: "要做打卡",
    frameId: "QaMP6",
    referenceImage: "uxpilot-export-09-27-26_11.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: ["NjcnH"],
  },
  {
    key: "checkin-avoid",
    groupId: "today-records",
    order: 7,
    title: "不要做打卡",
    frameId: "GzZMT",
    referenceImage: "uxpilot-export-09-27-26_04.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: ["U7hZQ6"],
  },
  {
    key: "edit-record",
    groupId: "today-records",
    order: 8,
    title: "修改记录",
    frameId: "USxd0",
    referenceImage: "uxpilot-export-09-27-26_12.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: ["DgoBX"],
  },
  {
    key: "backfill-record",
    groupId: "today-records",
    order: 9,
    title: "补记历史日期",
    frameId: "wGcr0",
    referenceImage: "uxpilot-export-09-27-26_26.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: ["c2laL"],
  },
  {
    key: "record-conflict",
    groupId: "today-records",
    order: 10,
    title: "记录冲突处理",
    frameId: "Mzx7h",
    referenceImage: "uxpilot-export-09-27-26_31.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: ["mmW9d"],
  },
  {
    key: "sync-feedback",
    groupId: "today-records",
    order: 11,
    title: "离线与同步反馈",
    frameId: "bXcUR",
    referenceImage: "uxpilot-export-09-27-26_30.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "ZT5sq",
      "hEAt2",
      "cITxP",
      "FHwDW",
      "hkIXg",
      "y7FRR",
      "IC3Zj",
      "p8oGT",
      "xgplI",
      "R15uaN",
      "irSAA",
      "Dkrkb",
      "NMzCZ",
      "qCBVm",
      "K5E1wn",
      "UJUSo",
      "nIybh",
      "h256KW",
      "dSiwi",
      "Q2GUQ",
      "D7iw7",
      "TkWFb",
      "rlm0d",
      "ch0TV",
      "fmtDW",
      "MZZZU",
    ],
  },
  {
    key: "calendar",
    groupId: "calendar",
    order: 12,
    title: "全局日历",
    frameId: "H6M9O1",
    referenceImage: "uxpilot-export-09-27-26_20.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "jLGMJ",
      "V1wKa",
      "q0G5iD",
      "stIDK",
      "oldJM",
      "Q2LHd",
      "yJCoN",
      "omfyr",
      "H9dVXM",
      "dFR47",
      "vaHaQ",
      "RBKYk",
      "gzyYh",
      "A4d1Z",
      "q5Jxs",
      "XayBM",
      "kW1Ta",
      "iJaN8",
      "dQQep",
      "YXZbv",
      "fsqyY",
      "dJ4Oe",
      "lPr9b",
      "T7qnt",
      "dq3m7",
    ],
  },
  {
    key: "plan-list",
    groupId: "plan-management",
    order: 13,
    title: "计划列表",
    frameId: "jPino",
    referenceImage: "uxpilot-export-09-27-26_18.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "t9t4z",
      "dbQqR",
      "PLviV",
      "NnEUW",
      "aQplb",
      "O8pgBX",
      "gYIjk",
      "IFBfo",
      "Bb42x",
      "E1x9An",
      "dzS0n",
      "zc4h9",
      "xBSqm",
      "Om8Kt",
      "nbCOo",
      "N2cVJ",
      "nKcgo",
      "LuMnb",
      "z0NSU",
      "ueyXu",
      "UHp7x",
      "vvHpp",
      "h095JJ",
      "bVWYZ",
      "xkbVm",
      "g3nKU",
      "Pphsv",
      "MAQWE",
      "WRo2M",
    ],
  },
  {
    key: "create-fixed",
    groupId: "plan-management",
    order: 14,
    title: "新建固定日期计划",
    frameId: "z94rpw",
    referenceImage: "uxpilot-export-09-27-26_06.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "rKrRL",
      "IiTnp",
      "X3G1j",
      "H3dEF",
      "P7OFTX",
      "o1qOkt",
      "fdQKp",
      "FAWHW",
      "w4iSY2",
      "SzCMQ",
      "xfSVV",
      "NixKE",
      "DRLSi",
      "VxhFc",
      "B3qpy5",
      "aMW3r",
      "egxFC",
      "XZ0UH",
      "d5q00X",
      "TSGZH",
      "P8GYr",
    ],
  },
  {
    key: "create-weekly",
    groupId: "plan-management",
    order: 15,
    title: "新建每周目标计划",
    frameId: "DrlJo",
    referenceImage: "uxpilot-export-09-27-26_23.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "lEsuS",
      "NyeWc",
      "ZoeBD",
      "Tlum0",
      "X8qplv",
      "hCC2q",
      "a1HtU",
      "h0b0v",
      "jl4MV",
      "QUjtn",
      "jUOCz",
      "aPxmE",
      "vq6i2",
      "b9u0y",
      "l1ATbs",
      "hPQ9H",
      "C7D95",
      "K8vjor",
      "Y6lqWP",
    ],
  },
  {
    key: "create-one-time",
    groupId: "plan-management",
    order: 16,
    title: "新建一次性任务",
    frameId: "vsuII",
    referenceImage: "uxpilot-export-09-27-26_01.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "gwZjL",
      "KiOup",
      "c17VUD",
      "JUb51",
      "UWGMy",
      "F08DB0",
      "Qvsh9",
      "NBysZ",
      "c38rD",
      "FTHWH",
      "HA2Hp",
      "kNf8p",
      "YAz7j",
      "RL1yt",
      "ijUMe",
      "alekc",
      "UBVOG",
      "h6ITvs",
      "HWku1",
      "de0kM",
      "yShBK",
      "AXAkZ",
    ],
  },
  {
    key: "edit-plan",
    groupId: "plan-management",
    order: 17,
    title: "编辑计划",
    frameId: "Qg1pJ",
    referenceImage: "uxpilot-export-09-27-26_17.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "JOAed",
      "o5Nq09",
      "OEGzo",
      "GLkVi",
      "yz88w",
      "OKu4B",
      "aXucW",
      "l2pZD",
      "S1IbT",
      "SXHgx",
      "jMVuM",
      "VfDxc",
      "Ty5vr",
      "vnTCw",
      "cJw2b",
      "OdjXs",
      "Gxzu7",
      "h3Whe",
      "qSJfo",
      "ZdIQr",
      "qnVYi",
      "awfcp",
      "RHRhR",
    ],
  },
  {
    key: "group-management",
    groupId: "plan-management",
    order: 18,
    title: "分组管理",
    frameId: "lPKOC",
    referenceImage: "uxpilot-export-09-27-26_21.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "tgMaC",
      "cqmDL",
      "S29ae",
      "kEzHm",
      "udx0Z",
      "E4Ell",
      "SetGn",
      "XifuA",
      "fj1pW",
      "TcJLA",
      "pfFQ5",
      "V8wBh5",
      "Nl1xo",
      "g3pgZL",
    ],
  },
  {
    key: "plan-confirmations",
    groupId: "plan-management",
    order: 19,
    title: "计划状态确认弹窗",
    frameId: "t56VJZ",
    referenceImage: "uxpilot-export-09-27-26_02.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "LEvK4",
      "kJQGr",
      "XTd3d",
      "bFphx",
      "gT3ge",
      "qO0Dy",
      "C7kUL",
      "iePMx",
      "WZW7Q",
      "Q1enKV",
      "zUyrg",
      "cxsDG",
    ],
  },
  {
    key: "plan-detail-fixed",
    groupId: "plan-details",
    order: 20,
    title: "固定日期计划详情",
    frameId: "mlcGv",
    referenceImage: "uxpilot-export-09-27-26_15.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "bx3gk",
      "ew7mE",
      "K2wiXX",
      "VNexf",
      "vXs2X",
      "l7Hur",
      "xrh19",
      "SWHjf",
      "GVYFg",
      "Vqx6x",
      "D3oJB6",
      "jYs8F",
      "bEudz",
      "atkfg",
      "vZ3eZ",
      "Z6kZ8",
      "e504n",
      "zCFES",
      "TGTtH",
      "s8BSoj",
      "zwZkS",
      "R9W4D",
    ],
  },
  {
    key: "plan-detail-weekly",
    groupId: "plan-details",
    order: 21,
    title: "每周目标计划详情",
    frameId: "IMmyc",
    referenceImage: "uxpilot-export-09-27-26_32.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "K6SBX",
      "QJKxa",
      "UkFDc",
      "VYVRK",
      "D7NfeF",
      "ecnTu",
      "bJVf8",
      "yyLwC",
      "bcccl",
      "VHCGh",
      "n6ZmwH",
      "a40NxI",
      "YSE08",
      "eEvVa",
      "v0eli",
      "dtptw",
      "nmNdp",
      "dEKlO",
      "QZypB",
      "PI4Gw",
    ],
  },
  {
    key: "plan-detail-one-time",
    groupId: "plan-details",
    order: 22,
    title: "一次性任务详情",
    frameId: "tZuml",
    referenceImage: "uxpilot-export-09-27-26_14.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "Kyj60",
      "UvtEc",
      "xvg3o",
      "BRwvF",
      "blSWe",
      "otQTa",
      "dXVw6",
      "rkAAT",
      "zcPTq",
      "Xtkxt",
      "OHIal",
      "Rw8Eh",
      "UQC8x",
      "ujVtN",
      "PfsCm",
      "YELAe",
      "v106X",
      "Y54i9g",
      "e9O0Cf",
      "eg595",
    ],
  },
  {
    key: "friends-list",
    groupId: "friends-sharing",
    order: 23,
    title: "朋友列表",
    frameId: "XD1pp",
    referenceImage: "uxpilot-export-09-27-26_09.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "mFYze",
      "X3EPAy",
      "QgF51",
      "yoOO1",
      "P20Yhb",
      "P0A6k",
      "LOmDU",
      "Rgaj9",
      "k8OtyY",
      "QoAtH",
      "ofGHB",
      "FHuv9",
      "w7Wv9r",
      "CD840",
      "wfMNF",
      "Q3MoM",
      "tA8Q4",
      "OGrlq",
      "g9NTpp",
      "T6FD8",
      "eyLD5",
      "W4iFT",
      "KPFQE",
      "SiKAK",
      "fiMBg",
    ],
  },
  {
    key: "friend-profile",
    groupId: "friends-sharing",
    order: 24,
    title: "朋友主页",
    frameId: "N1euu",
    referenceImage: "uxpilot-export-09-27-26_19.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "M1rh4U",
      "xF5XK",
      "pDqTR",
      "ELvoz",
      "NADn9",
      "t8IwDo",
      "yLf5d",
      "P5xWyR",
      "PgtMS",
      "YzDBc",
      "NTLoP",
      "z0PVVY",
      "USNAx",
      "uxuGm",
      "SfyqS",
      "cexL8",
      "QPaYk",
      "Ohovt",
      "RVppP",
      "drVtZ",
      "NV9wB",
      "Arrsq",
    ],
  },
  {
    key: "friend-readonly-detail",
    groupId: "friends-sharing",
    order: 25,
    title: "好友计划只读详情",
    frameId: "TeTWC",
    referenceImage: "uxpilot-export-09-27-26_28.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "LYDlm",
      "OBigU",
      "wLAgC",
      "Ez8Fg",
      "UBySn",
      "hax0q",
      "vg7Bl",
      "w1vDS",
      "o9e35b",
      "jVEBg",
      "KMaE1",
      "H3W0r",
      "BaEEH",
      "gCggt",
      "Plhfy",
      "E0JF1",
      "gDJL1",
      "Ho9BB",
      "xXpC4",
      "ZGzyz",
      "h6JOog",
    ],
  },
  {
    key: "select-share-friend",
    groupId: "friends-sharing",
    order: 26,
    title: "选择分享好友",
    frameId: "GOzpS",
    referenceImage: "uxpilot-export-09-27-26_05.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "d2IeCU",
      "BeavZ",
      "w51OKd",
      "Z4k1Pb",
      "VDBB1",
      "bZtBt",
      "Bo98E",
      "qKK8U",
      "KVK3i",
      "FgEOB",
      "T5yjrp",
      "LV34v",
      "aNCdL",
      "Rf6AE",
    ],
  },
  {
    key: "share-preview",
    groupId: "friends-sharing",
    order: 27,
    title: "分享预览",
    frameId: "MMIhD",
    referenceImage: "uxpilot-export-09-27-26_25.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "PRoEb",
      "hEsnt",
      "xRSw8",
      "kHB1F",
      "Ku67s",
      "yngBH",
      "mT57K",
      "qwlCh",
      "JZVdP",
      "KYwFw",
      "bmqih",
      "cCOAS",
      "Z8ftAq",
      "pCfUq",
    ],
  },
  {
    key: "share-permissions",
    groupId: "friends-sharing",
    order: 28,
    title: "分享权限设置",
    frameId: "N7LC5V",
    referenceImage: "uxpilot-export-09-27-26_16.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "os9ZK",
      "m2tOmz",
      "ijGFI",
      "FRqMS",
      "oZn5b",
      "JoZRx",
      "JYeHD",
      "wSk3i",
      "ufVVy",
      "Z95aH",
      "im1Tg",
      "MSf65",
      "qrbAi",
      "fFYTp",
      "X8Z3Sc",
      "hERnA",
      "g0I7A",
    ],
  },
  {
    key: "settings-home",
    groupId: "settings-data",
    order: 29,
    title: "设置首页",
    frameId: "ZLkv2",
    referenceImage: "uxpilot-export-09-27-26_10.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "D0kGck",
      "i1RmaL",
      "csAe7",
      "b3AVBB",
      "c0hY2E",
      "Q5JT7z",
      "CG9Nb",
      "pGoUX",
      "hqFJW",
      "AoA3O",
      "H1gqb",
      "wM2At",
      "fcTGS",
      "Y9Phtn",
      "nNeAf",
      "k3xUC",
      "VcvWv",
      "d9qqLY",
      "l3PYrr",
      "C4qUYd",
    ],
  },
  {
    key: "reminders",
    groupId: "settings-data",
    order: 30,
    title: "提醒设置",
    frameId: "CtzVR",
    referenceImage: "uxpilot-export-09-27-26_24.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "kwAFB",
      "xgEhh",
      "f3bv0",
      "x9m4t",
      "Trg8F",
      "vpVnF",
      "IaGBl",
      "oKhkl",
      "w751eQ",
      "B8DmQM",
      "R1uhaQ",
      "W2H6Zh",
      "Oede1",
      "G2nUh4",
      "wiXKg",
    ],
  },
  {
    key: "export-data",
    groupId: "settings-data",
    order: 31,
    title: "导出数据",
    frameId: "X9rXl",
    referenceImage: "uxpilot-export-09-27-26_22.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "p64Hbp",
      "iqgiE",
      "ZUGlb",
      "pXFet",
      "MOIc9",
      "m00G4",
      "Rw47b",
      "Asa2u",
      "ir87t",
      "IzHw1",
      "MCmrK",
      "GkQ11",
      "XJqTd",
      "X9YTHq",
      "f7EOk",
      "reTSJ",
      "DAhfB",
    ],
  },
  {
    key: "delete-account",
    groupId: "settings-data",
    order: 32,
    title: "删除账号",
    frameId: "Ytizk",
    referenceImage: "uxpilot-export-09-27-26_07.png",
    viewport: {
      width: 393,
      height: 852,
    },
    keyNodeIds: [
      "RcwY2",
      "Mnv9K",
      "VcoyS",
      "iT3Lq",
      "AxoJP",
      "VgTYA",
      "kUtF6",
      "WCJus",
      "nPMNf",
      "f5VRH",
      "CLYHf",
      "FZ2Hn",
      "PmvnB",
      "rU1wc",
      "twc8q",
      "ok6kW",
      "VVQR5",
      "jyWh7",
      "mJt9G",
      "BeMbu",
    ],
  },
] as const;
