// Generated from current Pen and docs/ui/web-style-map.json.
export const designSourceSha256 =
  "b1c94dbc01d577073a2c54ffa57f6953fbc4c6b07855fe4b9d829bce90479939";
export const uiCopy = {
  brand: "行迹",
  brandCaption: "安静地记录，诚实地回顾",
  phoneLabel: "手机号",
  privacy: "继续即代表同意《服务协议》和《隐私政策》",
  codeTitle: "输入验证码",
  profileTitle: "完善资料",
  profileCaption: "设置一个昵称，方便朋友认出你",
  todayEmptyTitle: "今天没有待处理的计划",
  todayEmptyCaption: "先创建一个计划，开始记录每一天",
  pendingHeading: "需要处理",
  weeklyHeading: "本周可记录",
  weeklyCaption: "每周目标类计划，本周内任意时间可记录",
  deadlineHeading: "截止事项",
  plansTitle: "计划",
  createTitle: "新建计划",
  nameDirection: "名称与方向",
  optionalHeading: "可选设置",
  historyHeading: "历史记录",
  phonePlaceholder: "请输入手机号",
  settingsTitle: "设置",
  notificationTitle: "提醒设置",
  exportTitle: "导出数据",
  doSuccess: "✓ 要做",
  readonlyHistory: "历史状态",
} as const;
export const uiNavigation = [
  {
    href: "/today",
    label: "今日",
    icon: "home",
    source: "today-active",
  },
  {
    href: "/calendar",
    label: "日历",
    icon: "calendar",
    source: "calendar",
  },
  {
    href: "/plans",
    label: "计划",
    icon: "list-checks",
    source: "plan-list",
  },
  {
    href: "/friends",
    label: "朋友",
    icon: "user",
    source: "friends-list",
  },
] as const;
export const uiPageSources = [
  {
    route: "/login",
    sources: ["phone-login", "sms-code"],
    component: "App.LoginPage",
    structure: [
      "brand-mark",
      "brand-title",
      "brand-caption",
      "phone-field",
      "submit",
      "privacy-note",
    ],
  },
  {
    route: "/setup",
    sources: ["profile-setup"],
    component: "App.SetupPage",
    structure: [
      "page-header",
      "profile-avatar",
      "profile-caption",
      "profile-form",
      "submit",
    ],
  },
  {
    route: "/today",
    sources: ["today-empty", "today-active"],
    component: "App.TodayPage",
    structure: [
      "date-timezone-avatar-header",
      "pending-section",
      "weekly-section",
      "deadline-section",
      "bottom-navigation",
    ],
  },
  {
    route: "record-dialog",
    sources: [
      "checkin-do",
      "checkin-avoid",
      "edit-record",
      "backfill-record",
      "record-conflict",
    ],
    component: "TodayCheckin",
    structure: [
      "bottom-sheet-header",
      "business-date",
      "result-selector",
      "failure-reason-if-needed",
      "optional-note-numeric-photos",
      "save",
    ],
  },
  {
    route: "/calendar",
    sources: ["calendar"],
    component: "CalendarPage",
    structure: [
      "title-today-action",
      "month-switcher",
      "seven-column-weekdays-dates",
      "status-legend",
      "bottom-navigation",
    ],
  },
  {
    route: "/plans",
    sources: ["plan-list"],
    component: "Plans.PlanList",
    structure: [
      "title-create-menu",
      "lifecycle-segments",
      "group-heading",
      "single-column-plan-cards",
      "bottom-navigation",
    ],
  },
  {
    route: "/plans/new",
    sources: ["create-fixed", "create-weekly", "create-one-time"],
    component: "Plans.PlanCreate",
    structure: [
      "page-header-save",
      "name-direction",
      "execution-method",
      "schedule-dates",
      "optional-settings",
      "save",
    ],
  },
  {
    route: "/plans/groups",
    sources: ["group-management"],
    component: "Plans.GroupManagementPage",
    structure: [
      "page-header",
      "group-create",
      "group-list",
      "plan-group-moves",
    ],
  },
  {
    route: "/plans/:id/edit",
    sources: ["edit-plan"],
    component: "Plans.PlanEdit",
    structure: [
      "page-header",
      "history-impact-note",
      "name-direction",
      "execution-dates",
      "numeric-settings",
      "save",
    ],
  },
  {
    route: "/plans/:id",
    sources: [
      "plan-detail-fixed",
      "plan-detail-weekly",
      "plan-detail-one-time",
    ],
    component: "Plans.PlanDetail",
    structure: [
      "page-header-edit",
      "title-badges-description",
      "statistics",
      "history-or-task-result",
      "share-entry",
      "lifecycle-actions",
    ],
  },
  {
    route: "plan-confirmation-dialog",
    sources: ["plan-confirmations"],
    component: "ModalDialog",
    structure: ["modal-title", "consequence-copy", "confirm", "safe-cancel"],
  },
  {
    route: "/friends",
    sources: ["friends-list"],
    component: "FriendsPage",
    structure: [
      "title-search-message-entry",
      "friend-list",
      "requests-sections",
      "bottom-navigation",
    ],
  },
  {
    route: "/friends/:id",
    sources: ["friend-profile"],
    component: "FriendSharedPage",
    structure: ["page-header", "avatar-nickname-username", "shared-plan-list"],
  },
  {
    route: "/shared-plans/:id",
    sources: ["friend-readonly-detail"],
    component: "SharedPlanPage",
    structure: [
      "page-header",
      "owner-plan-title",
      "readonly-rule-and-history",
      "encouragement",
    ],
  },
  {
    route: "/plans/:id/share",
    sources: ["select-share-friend", "share-preview", "share-permissions"],
    component: "ShareManager",
    structure: [
      "page-header",
      "current-permissions",
      "friend-selection",
      "server-sanitized-preview",
      "confirm-or-revoke",
    ],
  },
  {
    route: "/settings",
    sources: ["settings-home"],
    component: "App.SettingsPage",
    structure: [
      "page-header",
      "profile-card",
      "account-rows",
      "data-rows",
      "logout",
    ],
  },
  {
    route: "/settings/notifications",
    sources: ["reminders"],
    component: "NotificationSettings",
    structure: [
      "page-header",
      "delivery-switches",
      "per-plan-reminder-rules",
      "browser-permission",
    ],
  },
  {
    route: "/settings/export",
    sources: ["export-data"],
    component: "DataManagement.ExportsSection",
    structure: [
      "page-header",
      "format-content-description",
      "export-action",
      "download-progress",
    ],
  },
  {
    route: "/settings/delete",
    sources: ["delete-account"],
    component: "DataManagement.DeletionSection",
    structure: [
      "page-header",
      "consequence-notice",
      "export-entry",
      "confirmation-fields",
      "submit",
    ],
  },
] as const;
