version: "1.0"

# bitnami 镜像不能访问了
# 换官方
# docker postgres
# docker clickhouse

services:

  miaoma-pg-db:
    image: postgres:18
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
  miaoma-clickhouse-db:
    image: clickhouse:26.4