export type {
  CLSPerformancePayload,
  FCPPerformancePayload,
  FPSPerformancePayload,
  INPPerformancePayload,
  LCPPerformancePayload,
  LoAFPerformancePayload,
  PerformanceCapabilityMap,
  PerformanceMetricName,
  PerformanceMetricRating,
  PerformanceNavigationType,
  PerformancePayload,
  PerformanceSampleState,
  WebVitalPerformancePayload,
} from '@browser-monitor/protocol';
